<?php


use App\Node;
use PHPUnit\Framework\TestCase;

/**
 * Class NodeTest
 * @covers \App\Node
 */
class NodeTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
