<?php

namespace App;

use PHPUnit\Framework\TestCase;

/**
 * Class NodeTest
 * @package App\Node
 */
class NodeTest extends TestCase
{
    protected Node $node;

    /**
     * @covers \App\Node::setValue
     * @covers \App\Node::getValue
     */
    public function testValue()
    {
        $this->node->setValue(5);
        $this->assertEquals(5, $this->node->getValue());
    }

    /**
     * @covers \App\Node::setLeft
     * @covers \App\Node::getLeft
     */
    public function testLeft()
    {
        $left = new Node();
        $this->node->setLeft($left);
        $this->assertIsObject($this->node->getLeft());
        unset($left);
    }

    /**
     * @covers \App\Node::setRight
     * @covers \App\Node::getRight
     */
    public function testRight()
    {
        $right = new Node();
        $this->node->setRight($right);
        $this->assertIsObject($this->node->getRight());
        unset($right);
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->node = new Node();
    }

    public function tearDown(): void
    {
        unset($this->node);
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
